export interface Professional {
    id: number,
    image: string,
    name: string,
    status: boolean,
    cpf: string,
    rg: string,
    birthDate: string,
    address: string,
    street: string,
    number: string,
    neighborhood: string,
    currencyHour: string,
    service: string,
    regionActing: string,
    cep: string,
    uf: string,
    city: string,
    registerCfmCrm: string,
    specialty: string,
    created_at: string,
    email?: string,
    phone?: string,
}